import { MdAdd, MdEdit, MdDelete, MdCreditCard, MdAccountBalance, 
    MdEmail, MdFeaturedPlayList, MdAttachMoney, MdAttachEmail, 
    MdAutoGraph, MdRestaurant, MdDirectionsCar, MdSchool, MdHome, MdSportsSoccer, 
    MdShoppingCart, MdPets, MdFavorite, MdFitnessCenter, MdWallet, MdFlight, MdLocalCafe, 
    MdLocalBar, MdLocalHospital, MdLocalPharmacy,MdLocalGasStation, MdLocalMovies, MdLocalOffer,
    MdLocalParking, MdLocalPizza, MdLocalPlay, MdLocalShipping, MdLocalTaxi, MdWork,
    MdPhoneAndroid,
    MdComputer,
    MdLaptop,
    MdHeadset,
    MdMusicNote,
    MdBook,
    MdDirectionsBike,
    MdCake,
    MdBeachAccess,
    MdDirectionsBus,
    MdDirectionsBoat,
    MdDirectionsRailway,
    MdDirectionsWalk,
    MdEmojiEvents,
    MdEmojiFoodBeverage,
    MdEmojiPeople,
    MdEmojiNature,
    MdEmojiObjects,
    MdEmojiSymbols,
    MdEmojiTransportation,
    MdFastfood,
    MdLocalDrink,
    MdLocalDining,
    MdLocalFlorist,
    MdLocalGroceryStore,
    MdAddReaction,
    MdSave,
    Md4K,
    MdPhoneIphone,
} from 'react-icons/md'

export const enderecoServidor = 'http://localhost:3000';

export const listaCores = [
  "#000",
  "#111",
  "#222",
  "#333",
  "#444",
  "#555",
  "#666",
  "#777",
  "#888",
  "#999",
  "#fff",
  "#f8f8f8",
  "#e0e0e0",
  "#c0c0c0",
  "#a0a0a0",
  "#808080",
  "#606060",
  "#404040",
  "#008",
  "#007",
  "#006",
  "#005",
  "#00f",
  "#080",
  "#082",
  "#084",
  "#086",
  "#088",
  "#0f0",
  "#0f2",
  "#0f4",
  "#0f6",
  "#0f8",
  "#800",
  "#802",
  "#804",
  "#806",
  "#808",
  "#880",
  "#882",
  "#884",
  "#886",
  "#888",
  "#f00",
  "#f08",
  "#f80",
  "#f88",
  "#ff0",
  "#ff8",
  "#0ff",
  "#08f",
  "#80f",
  "#f0f",
  "#f0a",
  "#fa0",
  "#0fa",
  "#a0f",
  "#0af",
  "#af0",
  "#fa8",
  "#8af",
  "#a8f",
  "#8fa",
  "#41d3be",
  "#008080",
  "#e63946",
  "#f1faee",
  "#a8dadc",
  "#457b9d",
  "#1d3557",
  "#ffb703",
  "#fb8500",
];
export const listaIcones = [
  "restaurant",
  "directions-car",
  "school",
  "home",
  "sports-soccer",
  "shopping-cart",
  "pets",
  "favorite",
  "fitness-center",
  "wallet",
  "flight",
  "local-cafe",
  "local-bar",
  "local-hospital",
  "local-pharmacy",
  "local-gas-station",
  "local-movies",
  "local-offer",
  "local-parking",
  "local-pizza",
  "local-play",
  "local-shipping",
  "local-taxi",
  "work",
  "attach-money",
  "credit-card",
  "account-balance",
  "phone-android",
  "phone-iphone",
  "computer",
  "laptop",
  "headset",
  "music-note",
  "book",
  "cake",
  "beach-access",
  "directions-bus",
  "directions-bike",
  "directions-boat",
  "directions-railway",
  "directions-walk",
  "emoji-people",
  "emoji-events",
  "emoji-food-beverage",
  "emoji-nature",
  "emoji-objects",
  "emoji-symbols",
  "emoji-transportation",
  "fastfood",
  "local-dining",
  "local-drink",
  "local-florist",
  "local-grocery-store",
];

export const IconesCategorias = {
        'restaurant': <MdRestaurant className='w-6 h-6'/>,
        'directions-car': <MdDirectionsCar className='w-6 h-6'/>,
        "school": <MdSchool className='w-6 h-6'/>,
        "home": <MdHome className='w-6 h-6'/>,
        "sports-soccer": <MdSportsSoccer className='w-6 h-6'/>,
        "shopping-cart": <MdShoppingCart className='w-6 h-6'/>,
        "pets": <MdPets className='w-6 h-6'/>,
        "favorite": <MdFavorite className='w-6 h-6'/>,
        "fitness-center": <MdFitnessCenter className='w-6 h-6'/>,
        "wallet": <MdWallet className='w-6 h-6'/>,
        "flight": <MdFlight className='w-6 h-6'/>,
        "local-cafe": <MdLocalCafe className='w-6 h-6'/>,
        "local-bar": <MdLocalBar className='w-6 h-6'/>,
        "local-hospital": <MdLocalHospital className='w-6 h-6'/>,
        "local-pharmacy": <MdLocalPharmacy className='w-6 h-6'/>,
        "local-gas-station": <MdLocalGasStation className='w-6 h-6'/>,
        "local-movies": <MdLocalMovies className='w-6 h-6'/>,
        "local-offer": <MdLocalOffer className='w-6 h-6'/>  ,
        "local-parking": <MdLocalParking className='w-6 h-6'/>,
        "local-pizza": <MdLocalPizza className='w-6 h-6'/>,
        "local-play": <MdLocalPlay className='w-6 h-6'/>,
        "local-shipping": <MdLocalShipping className='w-6 h-6'/>,
        "local-taxi": <MdLocalTaxi className='w-6 h-6'/>,
        "work": <MdWork className='w-6 h-6'/>,
        "attach-money": <MdAttachMoney className='w-6 h-6'/>,
        "credit-card": <MdCreditCard className='w-6 h-6' />,
        "account-balance": <MdAccountBalance className='w-6 h-6' />,
        "phone-android": <MdPhoneAndroid className='w-6 h-6' />,
        "phone-iphone": <MdPhoneIphone className="w-6 h-6"/>,
        "computer": <MdComputer className='w-6 h-6' />,
        "laptop": <MdLaptop className='w-6 h-6' />,
        "headset": <MdHeadset className='w-6 h-6' />,
        "music-note" : <MdMusicNote className="w-6 h-6"/>,
        "book": <MdBook className='w-6 h-6' />,
        "cake": <MdCake className='w-6 h-6' />,
        "beach-access": <MdBeachAccess className='w-6 h-6' />,
        "directions-bus": <MdDirectionsBus className='w-6 h-6' />,
        "directions-bike" : <MdDirectionsBike className='w-6 h-6'/>,
        "directions-boat": <MdDirectionsBoat className='w-6 h-6'/>,
        "directions-railway": <MdDirectionsRailway className='w-6 h-6' />,
        "directions-walk": <MdDirectionsWalk className='w-6 h-6'/>,
        "emoji-people": <MdEmojiPeople className='w-6 h-6'/>,
        "emoji-events": <MdEmojiEvents className='w-6 h-6'/>,
        "emoji-food-beverage": <MdEmojiFoodBeverage className='w-6 h-6'/>,
        "emoji-nature": <MdEmojiNature className='w-6 h-6'/>,
        "emoji-objects": <MdEmojiObjects className='w-6 h-6'/>,
        "emoji-symbols": <MdEmojiSymbols className='w-6 h-6'/>,
        "emoji-transportation": <MdEmojiTransportation className='w-6 h-6'/>,
        "fastfood": <MdFastfood className='w-6 h-6'/>,
        "local-dining": <MdLocalDining className='w-6 h-6'/>,
        "local-drink": <MdLocalDrink className='w-6 h-6' />,
        "local-florist": <MdLocalFlorist className='w-6 h-6'/>,
        "local-grocery-store": <MdLocalGroceryStore className='w-6 h-6'/>,
        "add-reaction": <MdAddReaction className='w-6 h-6' />,
        "save": <MdSave className='w-6 h-6' />,
        "4k": <Md4K className='w-6 h-6'/>,
        "add": <MdAdd className='w-6 h-6'/>,
    }